# plots fraction of text covered by fraction of words
# words frequency is taken from file word_count_list.txt generated by word_count_list.py

from pylab import *

# read words count

file = open('word_count_list.txt')
count = []
total_words = []
for line in file:
    count.append(int(line.split()[1]))
    if len(total_words)>0:
        total_words.append(total_words[-1]+count[-1])
    else:
        total_words.append(count[-1])

print len(total_words)
print total_words[-1]

# fill scalled array 
# how many words are below this word in frequency
# how much of total text these words cover

scaled_count = []
scaled_total = []

l_count = len(count)
total = total_words[-1]

# this is for line
# x fraction of words cover (100 - x) fraction of text
x = 0;
x_n = 0;
y = 0;
delta_100_min = 100;

for i in range(l_count):
    scaled_count.append(float(i)/float(l_count)*100.0)
    scaled_total.append(float(float(total_words[i])/float(total))*100.0)
    if abs( 100 - scaled_count[i] - scaled_total[i] ) < delta_100_min:
        delta_100_min = 100 - scaled_count[i] - scaled_total[i] 
        x = scaled_count[i] 
        x_n = i
        y = scaled_total[i] 

print x,y
print x_n

# plot

figure(figsize=(8,8))
ax = axes([0.15, 0.15, 0.75, 0.75])
p1 = plot(scaled_count,scaled_total,linewidth=2.0) 

# plot line x -- (100 - x)
p2 = plot([x,x],[0,y],'r--')
p3 = plot([0,x],[y,y],'r--')

labels = ax.get_xticklabels()
setp(labels, fontsize=20)
labels = ax.get_yticklabels()
setp(labels, fontsize=20)

xlabel('fraction of words, %',fontsize=24);
ylabel('fraction of text, %',fontsize=24);

savefig('fraction.png',dpi=36)
show()
